/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardGroup: typeof import('bootstrap-vue-next')['BCardGroup']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BookmarksCards: typeof import('./src/components/BookmarksCards.vue')['default']
  }
}
