name: build-test-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: vue-cli-service
      run: yarn add -D @vue/cli-service-global @vue/cli
    - name: build
      run: yarn build
    - name: test
      run: yarn test:unit
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist